import { sidebar } from 'vuepress-theme-hope';

export const zhSidebar = sidebar({
  '/zh/latest/': [
    "README.md",
    {
      text: "开始",
      prefix: "start/",
      children: 'structure',
      icon: "launch",
      link: "start/README.md",
      collapsible: true,
    },
    {
      text: "部署",
      prefix: "deploy/",
      children: 'structure',
      link: "deploy/README.md",
      icon: "creative",
      collapsible: true,
    },
    {
      text: "开发",
      prefix: "develop/",
      children: 'structure',
      link: "develop/README.md",
      icon: "creative",
      collapsible: true,
    },
    {
      text: "管理",
      prefix: "manage/",
      children: 'structure',
      link: "manage/README.md",
      icon: "tool",
      collapsible: true,
    },
    {
      text: "指南",
      prefix: "reference/",
      children: 'structure',
      link: "reference/README.md",
      icon: "generic",
      collapsible: true,
    },
    {
      text: "生态",
      prefix: "eco/",
      children: 'structure',
      link: "eco/README.md",
      icon: "leaf",
      collapsible: true,
    },
    {
      text: "发布",
      prefix: "release/",
      children: 'structure',
      link: "release/README.md",
      icon: "copy",
      collapsible: true,
    },
  ],
  '/zh/v2.3/': [
    "README.md",
    {
      text: "开始",
      prefix: "start/",
      children: 'structure',
      icon: "launch",
      link: "start/README.md",
      collapsible: true,
    },
    {
      text: "部署",
      prefix: "deploy/",
      children: 'structure',
      link: "deploy/README.md",
      icon: "creative",
      collapsible: true,
    },
    {
      text: "开发",
      prefix: "develop/",
      children: 'structure',
      link: "develop/README.md",
      icon: "creative",
      collapsible: true,
    },
    {
      text: "管理",
      prefix: "manage/",
      children: 'structure',
      link: "manage/README.md",
      icon: "tool",
      collapsible: true,
    },
    {
      text: "指南",
      prefix: "reference/",
      children: 'structure',
      link: "reference/README.md",
      icon: "generic",
      collapsible: true,
    },
    {
      text: "生态",
      prefix: "eco/",
      children: 'structure',
      link: "eco/README.md",
      icon: "leaf",
      collapsible: true,
    },
    {
      text: "发布",
      prefix: "release/",
      children: 'structure',
      link: "release/README.md",
      icon: "copy",
      collapsible: true,
    },
  ],
});
