{
 "title": "CnosDB",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Quick overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" }
       ],
       "queryText": "SELECT DATE_BIN(INTERVAL '10 minutes', time, TIMESTAMP '1970-01-01T00:00:00Z') AS time, avg(\"usage_user\") FROM \"cpu\" WHERE $timeFilter GROUP BY DATE_BIN(INTERVAL '10 minutes', time, TIMESTAMP '1970-01-01T00:00:00Z') ORDER BY time ASC",
       "select": [
        [
         { "params": [ "uptime_format" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         { "params": [ "value" ], "type": "alias" }
        ]
       ],
       "table": "system"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "table": "disk"
      }
     ]
    },
    {
     "title": "LA (Medium)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "table": "system"
      }
     ]
    },
    {
     "title": "CPUs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "n_cpus" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "avg_n_cpus" ], "type": "alias" }
        ]
       ],
       "table": "system"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "queryText": "SELECT DATE_BIN(INTERVAL '1 minute', time, TIMESTAMP '1970-01-01T00:00:00Z') AS time, avg(\"usage_idle\") * -1 + 100 AS \"usage\" FROM \"cpu\" WHERE $timeFilter GROUP BY DATE_BIN(INTERVAL '1 minute', time, TIMESTAMP '1970-01-01T00:00:00Z') ORDER BY time ASC",
       "select": [
        [
         { "params": [ "usage_idle" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "usage" ], "type": "alias" }
        ]
       ],
       "table": "cpu"
      }
     ]
    },
    {
     "title": "RAM usage",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         }
        ]
       ],
       "table": "mem"
      }
     ]
    },
    {
     "title": "Swap Usage",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         }
        ]
       ],
       "table": "swap"
      }
     ]
    },
    {
     "title": "Users",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "n_users" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "table": "system"
      }
     ]
    }
   ]
  },
  {
   "title": "SYSTEM - CPU, Memory, Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "host" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         { "params": [ "cached" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "cached" ], "type": "alias" }
        ],
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "free" ], "type": "alias" }
        ],
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "buffered" ], "type": "alias" }
        ]
       ],
       "table": "mem"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "queryText": "SELECT DATE_BIN(INTERVAL '1 minute', time, TIMESTAMP '1970-01-01T00:00:00Z') AS time, avg(\"usage_user\") AS \"user\", avg(\"usage_system\") AS \"system\", avg(\"usage_softirq\") AS \"softirq\", avg(\"usage_nice\") AS \"nice\", avg(\"usage_irq\") AS \"irq\", avg(\"usage_iowait\") AS \"iowait\", avg(\"usage_guest\") AS \"guest\", avg(\"usage_guest_nice\") AS \"guest_nice\", avg(\"usage_steal\") AS \"steal\" FROM \"cpu\" WHERE $timeFilter GROUP BY DATE_BIN(INTERVAL '1 minute', time, TIMESTAMP '1970-01-01T00:00:00Z') ORDER BY time ASC",
       "select": [
        [
         { "params": [ "usage_user" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "user" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_system" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "system" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_softirq" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "softirq" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_nice" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "nice" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_irq" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "irq" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_iowait" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "iowait" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_guest" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "guest" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_guest_nice" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "guest_nice" ], "type": "alias" }
        ],
        [
         { "params": [ "usage_steal" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "steal" ], "type": "alias" }
        ]
       ],
       "table": "cpu"
      }
     ]
    },
    {
     "title": "CPU Load",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "load1" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "load1" ], "type": "alias" }
        ],
        [
         { "params": [ "load5" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "load5" ], "type": "alias" }
        ],
        [
         { "params": [ "load15" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "load15" ], "type": "alias" }
        ]
       ],
       "table": "system"
      }
     ]
    },
    {
     "title": "CPU usage per core",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "cpu" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "queryText": "SELECT DATE_BIN(INTERVAL '1 minute', time, TIMESTAMP '1970-01-01T00:00:00Z') AS time, cpu, (100 - avg(\"usage_idle\")) usage FROM \"cpu\" WHERE $timeFilter GROUP BY DATE_BIN(INTERVAL '1 minute', time, TIMESTAMP '1970-01-01T00:00:00Z'), \"cpu\" ORDER BY time ASC",
       "select": [
        [
         { "params": [ "usage_idle" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         }
        ]
       ],
       "table": "cpu"
      }
     ]
    },
    {
     "title": "Processes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "running" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "running" ], "type": "alias" }
        ],
        [
         { "params": [ "blocked" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "blocked" ], "type": "alias" }
        ],
        [
         { "params": [ "sleeping" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "sleeping" ], "type": "alias" }
        ],
        [
         { "params": [ "stopped" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "stopped" ], "type": "alias" }
        ],
        [
         { "params": [ "zombies" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "zombies" ], "type": "alias" }
        ],
        [
         { "params": [ "paging" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "paging" ], "type": "alias" }
        ],
        [
         { "params": [ "unknown" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "unknown" ], "type": "alias" }
        ]
       ],
       "table": "processes"
      }
     ]
    },
    {
     "title": "Context Switches",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "context_switches" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "context switches" ], "type": "alias" }
        ]
       ],
       "table": "kernel"
      }
     ]
    },
    {
     "title": "Root Disk usage (/)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "free" ], "type": "alias" }
        ]
       ],
       "table": "disk"
      }
     ]
    },
    {
     "title": "All partitions usage (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "used_percent" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "used_percent" ], "type": "alias" }
        ]
       ],
       "table": "disk"
      }
     ]
    },
    {
     "title": "Root (/) Disk inodes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "inodes_total" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "total" ], "type": "alias" }
        ],
        [
         { "params": [ "inodes_free" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "free" ], "type": "alias" }
        ],
        [
         { "params": [ "inodes_used" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "used" ], "type": "alias" }
        ]
       ],
       "table": "disk"
      }
     ]
    },
    {
     "title": "All partitions Inodes (Free)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "queryText": "SELECT DATE_BIN(INTERVAL '1 minute', time, TIMESTAMP '1970-01-01T00:00:00Z') AS time, avg(\"inodes_free\") AS \"free\" FROM \"disk\" WHERE $timeFilter GROUP BY DATE_BIN(INTERVAL '1 minute', time, TIMESTAMP '1970-01-01T00:00:00Z') ORDER BY time ASC",
       "select": [
        [
         { "params": [ "inodes_free" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "free" ], "type": "alias" }
        ]
       ],
       "table": "disk"
      }
     ]
    },
    {
     "title": "Swap usage (bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "free" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "free" ], "type": "alias" }
        ],
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "used" ], "type": "alias" }
        ],
        [
         { "params": [ "total" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "total" ], "type": "alias" }
        ]
       ],
       "table": "swap"
      }
     ]
    },
    {
     "title": "Swap I/O bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "in" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "in" ], "type": "alias" }
        ],
        [
         { "params": [ "out" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "table": "swap"
      }
     ]
    },
    {
     "title": "Disk I/O requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "reads" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "table": "diskio"
      },
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "writes" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "table": "diskio"
      }
     ]
    },
    {
     "title": "Disk I/O time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "read_time" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "table": "diskio"
      },
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "write_time" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "table": "diskio"
      }
     ]
    },
    {
     "title": "Disk I/O bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "read_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "read" ], "type": "alias" }
        ]
       ],
       "table": "diskio"
      },
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "write_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "write" ], "type": "alias" }
        ]
       ],
       "table": "diskio"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "bytes_recv" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "table": "net"
      },
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "bytes_sent" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "table": "net"
      }
     ]
    },
    {
     "title": "Network Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "packets_recv" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "table": "net"
      },
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "packets_sent" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "table": "net"
      }
     ]
    },
    {
     "title": "TCP connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "tcp_close" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "CLOSED" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_close_wait" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "CLOSE_WAIT" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_closing" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "CLOSING" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_established" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "ESTABLISHED" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait1" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "FIN_WAIT" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_fin_wait2" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "FIN_WAIT2" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_last_ack" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "LAST_ACK" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_recv" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "SYN_RECV" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_syn_sent" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "SYN_SENT" ], "type": "alias" }
        ],
        [
         { "params": [ "tcp_time_wait" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "TIME_WAIT" ], "type": "alias" }
        ]
       ],
       "table": "netstat"
      }
     ]
    },
    {
     "title": "TCP handshake issues",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "tcp_outrsts" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "tcp_outrsts" ], "type": "alias" }
        ]
       ],
       "table": "net"
      },
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "tcp_activeopens" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "tcp_activeopens" ], "type": "alias" }
        ]
       ],
       "table": "net"
      },
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "tcp_estabresets" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "tcp_estabresets" ], "type": "alias" }
        ]
       ],
       "table": "net"
      },
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "tcp_passiveopens" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "tcp_passiveopens" ], "type": "alias" }
        ]
       ],
       "table": "net"
      }
     ]
    },
    {
     "title": "Packets Drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "drop_in" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "drop_in" ], "type": "alias" }
        ]
       ],
       "table": "net"
      },
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "drop_out" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         }
        ]
       ],
       "table": "net"
      }
     ]
    },
    {
     "title": "Packets Error",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "err_in" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "in" ], "type": "alias" }
        ]
       ],
       "table": "net"
      },
      {
       "fill": "null",
       "groupBy": [
        { "params": [ "1 minute" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "err_out" ], "type": "field" },
         {
          "params": [],
          "type": "avg"
         },
         { "params": [ "out" ], "type": "alias" }
        ]
       ],
       "table": "net"
      }
     ]
    }
   ]
  }
 ]
}